name: slack weather action

on: [push]
# on:
#   schedule:
#     - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 소스코드를 ubuntu 에 복사
    - name: 소스코드를 ubuntu 에 복사
      uses: actions/checkout@v2
    # ubuntu 에 python 개발환경 구축
    - name: ubuntu 에 python 개발환경 구축
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    # python 모듈 설치
    - name: python 모듈 설치
      run: pip install -r req.txt
    # python main.py 명령어 실행
    - name: python main.py 명령어 실행
      env:
        slack_token: ${{ secrets.SLACK_TOKEN }}
      run: python main.py